name: Sample Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: URL Checker
        uses: paramt/url-checker@v0.2.0
        with:
          files: "README.md,SUPPORT.md"
